#!/usr/bin/env ruby

require "bundler/setup"
require "byebug"
require "mattlang"

$stdout.sync = true

filename = ARGV.first

if filename
  Mattlang::Interpreter.interpret_file(filename)
else
  Mattlang::REPL.start
end
