#!/usr/bin/env ruby

require "bundler/setup"
require "mattlang"

filename = ARGV.first

if filename
  Mattlang::Interpreter.new(File.read(filename)).interpret
else
  puts "Provide the name of a file to run"
end
